import { FontAwesome5 } from '@expo/vector-icons';
import PropTypes from 'prop-types';
import React from 'react';
import { AsyncStorage, View } from 'react-native';
import AuthTextField from '../../components/AuthTextField';
import { BigTitle, ButtonLabel, FilledButtonContainer, Subhead } from '../../components/BaseComponents';
import Colors from '../../constants/Colors';
import { getCustomersById, updateCustomers } from '../../lib/airtable/request';
import { signUpFields } from '../../lib/authUtils';
import { AuthScreenContainer, BackButton, FormContainer } from '../../styled/auth';


export default class NameChangeScreen extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            customer: null,
            confirmed: false,
            success: false,
            values: {
                [signUpFields.NAME]: '',
            },
            errors: {
                [signUpFields.NAME]: '',
            },
        };
    }

    // Load customer record & transactions
    async componentDidMount() {
        const customerId = await AsyncStorage.getItem('customerId');
        try {
            const customer = await getCustomersById(customerId);

            this.setState({ customer });
        } catch (err) {
            console.error(err);
        }
    }

    // Check for an error with updated text
    // Set errors and updated text in state
    updateError = async (text, signUpField) => {
        let error = false;
        let errorMsg = '';
        // const fieldValue = this.state.values[signUpField];
        // validate returns null if no error is found
        switch (signUpField) {
            case signUpFields.NAME:
                error = !text.replace(/\s/g, '').length;
                if (error) errorMsg = 'Name cannot be blank';
                break;
            default:
                console.log('Not reached');
        }
        if (error) { this.setState({ confirmed: false }); }
        else {
            this.setState({ confirmed: true });
        }
        this.setState(prevState => ({
            errors: { ...prevState.errors, [signUpField]: errorMsg },
            values: { ...prevState.values, [signUpField]: text },
        }));

        return error;
    };

    // onBlur callback is required in case customer taps on field, does nothing, and taps out
    onBlur = async signUpField => {
        await this.updateError(signUpField);
    };

    // onTextChange does a check before updating errors
    // It can only remove errors, not trigger them
    onTextChange = async (text, signUpField) => {
        // Only update error if there is currently an error
        // Unless field is password, since it is generally the last field to be filled out

        this.setState(prevState => ({
            values: { ...prevState.values, [signUpField]: text },
        }));

    };

    changeName = async () => {
        // We use the record ID generated by Airtable as the salt to encrypt
        // Update the created record with the encrypted password
        await updateCustomers(this.state.customer.id, { name: this.state.values[signUpFields.NAME] });
        this.setState({ success: true });
    }

    render() {
        return (
            <AuthScreenContainer>
                <BackButton onPress={() => this.props.navigation.goBack()}>
                    <FontAwesome5 name="arrow-left" solid size={24} />
                </BackButton>
                {!this.state.success &&
                    <View>
                        <BigTitle>Set Your New Name</BigTitle>
                        <FormContainer>
                            <AuthTextField
                                fieldType="Name"
                                value={this.state.values[signUpFields.NAME]}
                                onBlurCallback={(value) =>
                                    this.updateError(value, signUpFields.NAME)
                                }
                                changeTextCallback={async (text) =>
                                    this.onTextChange(text, signUpFields.NAME)
                                }
                                error={this.state.errors[signUpFields.NAME]}
                            />
                        </FormContainer>
                        <FilledButtonContainer
                            style={{ marginTop: 48 }}
                            color={
                                !this.state.confirmed ? Colors.lightestGreen : Colors.primaryGreen
                            }
                            width="100%"
                            onPress={() =>
                                this.changeName()
                            }
                            disabled={!this.state.confirmed}>
                            <ButtonLabel color={Colors.lightest}>Change Name</ButtonLabel>
                        </FilledButtonContainer>
                    </View>
                }

                {this.state.success &&
                    <View>
                        <BigTitle>Success!</BigTitle>
                        <Subhead style={{ marginTop: 32 }}>Your name has been changed.</Subhead>
                        <FilledButtonContainer
                            style={{ marginTop: 48 }}
                            color={Colors.primaryGreen}
                            width="100%"
                            onPress={() =>
                                this.props.navigation.goBack()
                            }
                        >
                            <ButtonLabel color={Colors.lightest}>Back To Settings</ButtonLabel>
                        </FilledButtonContainer>
                    </View>
                }
            </AuthScreenContainer>
        );
    }
}

NameChangeScreen.propTypes = {
    navigation: PropTypes.object.isRequired,
};
