/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/

export const Tables = {
  Customers: 'Customers',
  Clerks: 'Clerks',
  Stores: 'Stores',
  Products: 'Products',
  Resources: 'Resources',
  Transactions: 'Transactions',
  LineItems: 'Line Items',
  PushTokens: 'Push Tokens',
  News: 'News',
  Recipes: 'Recipes',
};

export const Columns = {
  Customers: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    phoneNumber: { name: `Phone Number`, type: `phone` },
    password: { name: `Password`, type: `text` },
    points: { name: `Points`, type: `number` },
    rewardsAvailable: { name: `Rewards Available`, type: `formula` },
    transactionIds: { name: `Transactions`, type: `foreignKey-many` },
    pushTokenIds: { name: `Push Tokens`, type: `foreignKey-many` },
    rewardsRedeemed: { name: `Rewards Redeemed`, type: `number` },
    id: { name: `id`, type: `formula` },
    name: { name: `Name`, type: `text` },
    tokenNames: { name: `Token Names`, type: `lookup` },
    favoriteStoreIds: { name: `Favorite Stores`, type: `foreignKey-many` },
    generalNotifications: { name: `General Notifications`, type: `select` },
    deliveryNotifications: { name: `Delivery Notifications`, type: `select` },
    notifications: { name: `Notifications`, type: `checkbox` },
  },
  Clerks: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    firstName: { name: `First Name`, type: `text` },
    lastName: { name: `Last Name`, type: `text` },
    pin: { name: `PIN`, type: `text` },
    transactionIds: { name: `Transactions`, type: `foreignKey-many` },
    storeId: { name: `Store`, type: `foreignKey-one` },
    clerkName: { name: `Clerk Name`, type: `formula` },
    id: { name: `id`, type: `formula` },
    storeName: { name: `Store Name`, type: `lookup` },
  },
  Stores: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    ward: { name: `Ward`, type: `text` },
    address: { name: `Address`, type: `text` },
    storeHours: { name: `Store Hours`, type: `text` },
    snapOrEbtAccepted: { name: `SNAP or EBT Accepted`, type: `checkbox` },
    couponProgramPartner: { name: `Coupon Program Partner`, type: `checkbox` },
    transactionIds: { name: `Transactions`, type: `foreignKey-many` },
    latitude: { name: `Latitude`, type: `number` },
    longitude: { name: `Longitude`, type: `number` },
    id: { name: `id`, type: `formula` },
    clerkIds: { name: `Clerks`, type: `foreignKey-many` },
    productIds: { name: `Products`, type: `foreignKey-many` },
    storeName: { name: `Store Name`, type: `text` },
    rewardsAccepted: { name: `Rewards Accepted`, type: `checkbox` },
    phoneNumber: { name: `Phone Number`, type: `phone` },
    wic: { name: `WIC`, type: `checkbox` },
    favoritedCustomerIds: {
      name: `Favorited Customers`,
      type: `foreignKey-many`,
    },
    doNotDisplay: { name: `Do Not Display`, type: `checkbox` },
    stocksOtherVendors: { name: `Stocks Other Vendors`, type: `checkbox` },
    latestDelivery: { name: `Latest Delivery`, type: `date` },
  },
  Products: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    category: { name: `Category`, type: `multiSelect` },
    points: { name: `Points`, type: `formula` },
    multiplier: { name: `Multiplier`, type: `number` },
    id: { name: `id`, type: `formula` },
    lineItemIds: { name: `Line Items`, type: `foreignKey-many` },
    name: { name: `Name`, type: `text` },
    storeIds: { name: `Stores`, type: `foreignKey-many` },
    image: { name: `Image`, type: `multipleAttachment` },
    detail: { name: `Detail`, type: `text` },
    fullName: { name: `Full Name`, type: `formula` },
    fullSizeImage: { name: `Full Size Image`, type: `multipleAttachment` },
    customerCost: { name: `Customer Cost`, type: `number` },
  },
  Resources: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    url: { name: `URL`, type: `text` },
    description: { name: `Description`, type: `text` },
    category: { name: `Category`, type: `multiSelect` },
    title: { name: `Title`, type: `text` },
    id: { name: `id`, type: `formula` },
  },
  Transactions: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    storeId: { name: `Store`, type: `foreignKey-one` },
    productsPurchasedIds: {
      name: `Products Purchased`,
      type: `foreignKey-many`,
    },
    customerId: { name: `Customer`, type: `foreignKey-one` },
    receipts: { name: `Receipts`, type: `text` },
    date: { name: `Date`, type: `formula` },
    pointsEarned: { name: `Points Earned`, type: `number` },
    clerkId: { name: `Clerk`, type: `foreignKey-one` },
    customerName: { name: `Customer Name`, type: `lookup` },
    lineItems: { name: `Line Items`, type: `lookup` },
    storeName: { name: `Store Name`, type: `lookup` },
    id: { name: `id`, type: `formula` },
    rewardsApplied: { name: `Rewards Applied`, type: `number` },
    currentPoints: { name: `Current Points`, type: `number` },
    totalSale: { name: `Total Sale`, type: `number` },
    discount: { name: `Discount`, type: `number` },
    subtotal: { name: `Subtotal`, type: `number` },
  },
  'Line Items': {
    primaryKey: { name: `Primary Key`, type: `formula` },
    productId: { name: `Product`, type: `foreignKey-one` },
    quantity: { name: `Quantity`, type: `number` },
    totalPrice: { name: `Total price`, type: `formula` },
    productPrice: { name: `Product price`, type: `lookup` },
    transactionId: { name: `Transaction`, type: `foreignKey-one` },
    productFullName: { name: `Product Full Name`, type: `lookup` },
    id: { name: `id`, type: `formula` },
  },
  'Push Tokens': {
    primaryKey: { name: `Primary Key`, type: `formula` },
    created: { name: `Created`, type: `formula` },
    customerIds: { name: `Customers`, type: `foreignKey-many` },
    customerName: { name: `Customer Name`, type: `lookup` },
    token: { name: `Token`, type: `text` },
    id: { name: `id`, type: `formula` },
  },
  News: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    created: { name: `Created`, type: `formula` },
    description: { name: `Description`, type: `multilineText` },
    id: { name: `id`, type: `formula` },
    postDate: { name: `Post Date`, type: `date` },
    title: { name: `Title`, type: `text` },
  },
  Recipes: {
    primaryKey: { name: `Primary Key`, type: `formula` },
    servings: { name: `Servings`, type: `text` },
    prepTimeminutes: { name: `Prep Time (Minutes)`, type: `text` },
    cookTimeminutes: { name: `Cook Time (Minutes)`, type: `text` },
    ingredients: { name: `Ingredients`, type: `multilineText` },
    instructions: { name: `Instructions`, type: `multilineText` },
    title: { name: `Title`, type: `text` },
    id: { name: `id`, type: `formula` },
    image: { name: `Image`, type: `multipleAttachment` },
  },
};
