/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/

export const Tables = {
	Customers: 'Customers',
	PushTokens: 'Push Tokens',
	Clerks: 'Clerks',
	Stores: 'Stores',
	Products: 'Products',
	LineItems: 'Line Items',
	Transactions: 'Transactions',
	Recipes: 'Recipes',
	Resources: 'Resources',
	News: 'News',
	Receipts: 'Receipts',
};

export const Columns = {
	"Customers": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		phoneNumber: {name:`Phone Number`, type:`phone`},
		password: {name:`Password`, type:`text`},
		points: {name:`Points`, type:`number`},
		rewardsAvailable: {name:`Rewards Available`, type:`formula`},
		transactionIds: {name:`Transactions`, type:`foreignKey-many`},
		receiptIds: {name:`Receipts`, type:`foreignKey-many`},
		pushTokenIds: {name:`Push Tokens`, type:`foreignKey-many`},
		rewardsRedeemed: {name:`Rewards Redeemed`, type:`number`},
		id: {name:`id`, type:`formula`},
		name: {name:`Name`, type:`text`},
		tokenNames: {name:`Token Names`, type:`lookup`},
	},
	"Push Tokens": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		created: {name:`Created`, type:`formula`},
		customerIds: {name:`Customers`, type:`foreignKey-many`},
		customerName: {name:`Customer Name`, type:`lookup`},
		token: {name:`Token`, type:`text`},
		id: {name:`id`, type:`formula`},
	},
	"Clerks": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		firstName: {name:`First Name`, type:`text`},
		lastName: {name:`Last Name`, type:`text`},
		pin: {name:`PIN`, type:`text`},
		transactionIds: {name:`Transactions`, type:`foreignKey-many`},
		storeId: {name:`Store`, type:`foreignKey-one`},
		clerkName: {name:`Clerk Name`, type:`formula`},
		id: {name:`id`, type:`formula`},
		storeName: {name:`Store Name`, type:`lookup`},
	},
	"Stores": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		ward: {name:`Ward`, type:`text`},
		address: {name:`Address`, type:`text`},
		storeHours: {name:`Store Hours`, type:`text`},
		snapOrEbtAccepted: {name:`SNAP or EBT Accepted`, type:`checkbox`},
		couponProgramPartner: {name:`Coupon Program Partner`, type:`checkbox`},
		transactionIds: {name:`Transactions`, type:`foreignKey-many`},
		latitude: {name:`Latitude`, type:`number`},
		longitude: {name:`Longitude`, type:`number`},
		id: {name:`id`, type:`formula`},
		clerkIds: {name:`Clerks`, type:`foreignKey-many`},
		productIds: {name:`Products`, type:`foreignKey-many`},
		storeName: {name:`Store Name`, type:`text`},
		rewardsAccepted: {name:`Rewards Accepted`, type:`checkbox`},
		phoneNumber: {name:`Phone Number`, type:`phone`},
		wic: {name:`WIC`, type:`checkbox`},
	},
	"Products": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		category: {name:`Category`, type:`multiSelect`},
		points: {name:`Points`, type:`formula`},
		multiplier: {name:`Multiplier`, type:`number`},
		id: {name:`id`, type:`formula`},
		lineItemIds: {name:`Line Items`, type:`foreignKey-many`},
		name: {name:`Name`, type:`text`},
		storeIds: {name:`Stores`, type:`foreignKey-many`},
		image: {name:`Image`, type:`multipleAttachment`},
		detail: {name:`Detail`, type:`text`},
		fullName: {name:`Full Name`, type:`formula`},
		fullSizeImage: {name:`Full Size Image`, type:`multipleAttachment`},
		customerCost: {name:`Customer Cost`, type:`number`},
	},
	"Line Items": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		productId: {name:`Product`, type:`foreignKey-one`},
		quantity: {name:`Quantity`, type:`number`},
		totalPrice: {name:`Total price`, type:`formula`},
		productPrice: {name:`Product price`, type:`lookup`},
		transactionId: {name:`Transaction`, type:`foreignKey-one`},
		productFullName: {name:`Product Full Name`, type:`lookup`},
		id: {name:`id`, type:`formula`},
	},
	"Transactions": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		storeId: {name:`Store`, type:`foreignKey-one`},
		productsPurchaseIds: {name:`Products Purchased`, type:`foreignKey-many`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
		receiptIds: {name:`Receipts`, type:`foreignKey-many`},
		date: {name:`Date`, type:`formula`},
		pointsEarned: {name:`Points Earned`, type:`number`},
		clerkId: {name:`Clerk`, type:`foreignKey-one`},
		customerName: {name:`Customer Name`, type:`lookup`},
		lineItems: {name:`Line Items`, type:`lookup`},
		storeName: {name:`Store Name`, type:`lookup`},
		id: {name:`id`, type:`formula`},
		rewardsApplied: {name:`Rewards Applied`, type:`number`},
		currentPoints: {name:`Current Points`, type:`number`},
		totalSale: {name:`Total Sale`, type:`number`},
		discount: {name:`Discount`, type:`number`},
		subtotal: {name:`Subtotal`, type:`number`},
	},
	"Recipes": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		servings: {name:`Servings`, type:`text`},
		prepTimeminutes: {name:`Prep Time (minutes)`, type:`text`},
		cookTimeminutes: {name:`Cook Time (minutes)`, type:`text`},
		ingredients: {name:`Ingredients`, type:`text`},
		instructions: {name:`Instructions`, type:`text`},
		title: {name:`Title`, type:`text`},
		id: {name:`id`, type:`formula`},
	},
	"Resources": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		url: {name:`URL`, type:`multilineText`},
		description: {name:`Description`, type:`text`},
		category: {name:`Category`, type:`select`},
		title: {name:`Title`, type:`text`},
		id: {name:`id`, type:`formula`},
	},
	"News": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		created: {name:`Created`, type:`formula`},
		description: {name:`Description`, type:`multilineText`},
		id: {name:`id`, type:`formula`},
		postDate: {name:`Post Date`, type:`date`},
		title: {name:`Title`, type:`text`},
	},
	"Receipts": {
		primaryKey: {name:`Primary Key`, type:`formula`},
		transactionId: {name:`Transaction`, type:`foreignKey-one`},
		attachments: {name:`Attachments`, type:`multipleAttachment`},
		time: {name:`Time`, type:`date`},
		customerId: {name:`Customer`, type:`foreignKey-one`},
		customerName: {name:`Customer Name`, type:`lookup`},
		id: {name:`id`, type:`formula`},
	},
};
